# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "SequentialRNN": "02_text.models.core.ipynb",
         "SentenceEncoder": "02_text.models.core.ipynb",
         "masked_concat_pool": "02_text.models.core.ipynb",
         "PoolingLinearClassifier": "02_text.models.core.ipynb",
         "get_text_classifier": "02_text.models.core.ipynb",
         "text_classifier_learner": "03_text.learner.ipynb"}

modules = ["core.py",
           "text/models/core.py",
           "text/learner.py"]

doc_url = "https://debjyotiSRoy.github.io/xcube/"

git_url = "https://github.com/debjyotiSRoy/xcube/tree/master/"

def custom_doc_links(name): return None
