# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"namestr": "00_utils.ipynb",
         "list_files": "00_utils.ipynb",
         "get_paths": "00_utils.ipynb",
         "plot_reduction": "00_utils.ipynb",
         "LinBnDrop": "01_layers.ipynb",
         "XMLAttention": "01_layers.ipynb",
         "SequentialRNN": "02_text.models.core.ipynb",
         "SentenceEncoder": "02_text.models.core.ipynb",
         "AttentiveSentenceEncoder": "02_text.models.core.ipynb",
         "masked_concat_pool": "02_text.models.core.ipynb",
         "PoolingLinearClassifier": "02_text.models.core.ipynb",
         "OurPoolingLinearClassifier": "02_text.models.core.ipynb",
         "LabelAttentionClassifier": "02_text.models.core.ipynb",
         "LabelAttentionClassifier2": "02_text.models.core.ipynb",
         "LabelAttentionClassifier3": "02_text.models.core.ipynb",
         "get_text_classifier": "02_text.models.core.ipynb",
         "text_classifier_learner": "03_text.learner.ipynb",
         "PrecisionK": "04_metrics.ipynb",
         "PrecisionR": "04_metrics.ipynb"}

modules = ["utils.py",
           "layers.py",
           "text/models/core.py",
           "text/learner.py",
           "metrics.py"]

doc_url = "https://debjyotiSRoy.github.io/xcube/"

git_url = "https://github.com/debjyotiSRoy/xcube/tree/master/"

def custom_doc_links(name): return None
